spring:
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: ${DN_URL}
        username: ${DB_USERNAME}
        password: ${DB_PWD}
    jpa:
        hibernate:
            ddl-auto: create
        database: mysql
        generate-ddl: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    main:
        allow-bean-definition-overriding: true # userDetailService ?? ??? ?? ?? ??? ??? ??? ??? ?? ??
server:
    port: 8081 # ?? ??

jwt:
    header: ${JWT_HEADER}
    prefix: ${JWT_PREFIX}
    secretKey: ${JWT_SECRET_KEY}
    accessExp: ${JWT_ACCESS_EXP}
    refreshExp: ${JWT_REFRESH_EXP}